### ISSUE TITLE
Plugin not working for me on Android 

### ISSUE THREAD

**Issue by abhayastudios** [mdanishs/nativescript-toasts#3]
On the iOS simulator the plugin is working just fine for me, but on a real Android device I'm getting the error below:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onTouch failed

[object Object]
File: "/data/data/<app>/files/app/tns_modules/ui/gestures/gestures.js, line: 97, column: 40

StackTrace: 
	Frame: function:'GesturesObserver.androidOnTouchEvent', file:'/data/data/<app>/files/app/tns_modules/ui/gestures/gestures.js', line: 97, column: 41
	Frame: function:'onTouch', file:'/data/data/<app>/files/app/tns_modules/ui/core/view.js', line: 113, column: 37


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.gen.android.view.View_OnTouchListener.onTouch(android.view.View$OnTouchListener.java)
	at android.view.View.dispatchTouchEvent(View.java:8962)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5306)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2568)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1776)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2529)
	at android.view.View.dispatchPointerEvent(View.java:9173)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4706)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4544)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6454)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6425)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6654)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

Any idea what this may be about? I am using a very simple test case according to the docs where I import the Toast and then within the class I have a method that I call to show the toast:

```
import * as Toast from 'nativescript-toasts';
[...]
export class SomePage {
  constructor()

  public showToast(message:string) {
    Toast.show({
      text: message, 
      duration: Toast.DURATION.SHORT
    });
  }
}
```

This is the version info for the tns cli:

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.0           │ 2.4.1          │ Update available │
│ tns-core-modules │ 2.4.0           │ 2.4.2          │ Update available │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

**Comment by abhayastudios** [comment]
Sorry seems like the issue is not with the plugin but I am guessing with something in the NS ui itself (I was wondering how gestures were related to the toast).
